Get the random effect conditional standard deviations (similar to standard errors)
ucgmsim/mera pull request #6
Opened 2024-06-24 04:03 UTC by AndrewRidden-Harper

These modifications get the random effect conditional standard deviations (similar to standard errors) for events and (optionally) sites. These modifications rely on a modified version of [Pymer4](https://github.com/ucgmsim/pymer4/tree/get_ranef_cond_std)

2024-06-25 22:40 UTC, AndrewRidden-Harper commented
This PR is ready for everyone to review now.
@lispandfound you might be interested to know the resolution to the issue I told you about where the site and event names seemed to change going from R to Python. The data transfer was actually working properly, it was just a more complicated data structure. Python was getting an R FactorVector which is an array of R indices that correspond to an index in an array of unique strings which can be accessed with an attribute in Python. So I just had to get the unique strings and then use the indices to recover the actual site and event names.

2024-06-26 03:03 UTC, lispandfound requested changes
not too many small changes I'd like to see. Otherwise looks good.

2024-06-26 03:03 UTC, lispandfound commented on mera/mera_pymer4.py
> +class MeraResults(NamedTuple):
Is there any reason why this is a `NamedTuple` over a dataclass? I would've thought dataclasses would be the way to go here because you do not make use of the (anti-)features of named tuples.

2024-06-26 03:03 UTC, lispandfound commented on wiki/Home.md
> +the black line labelled $\mu_{\textrm{group}} that passes through the approximate center of all data points.
I think you dropped this: `$`
```suggestion
the black line labelled $\mu_{\textrm{group}}$ that passes through the approximate center of all data points. 
```

2024-06-26 03:03 UTC, lispandfound commented on wiki/Home.md
> +[link.](https://www.pythonfordatascience.org/mixed-effects-regression-python/)](images/variable_intercept.png)
It's worth noting that your lovely caption will not show up in the rendering of the wiki. Instead it is simply the HTML `alt` attribute for the image.

2024-06-26 03:03 UTC, lispandfound commented on mera/mera_pymer4.py
>      ims: List[str],
No need for `List` anymore.
```suggestion
    ims: list[str],
```

2024-06-26 03:03 UTC, lispandfound commented on mera/mera_pymer4.py
> +from typing import List, Optional, NamedTuple
Don't need `List` import (see below). Also these should be sorted properly.
```suggestion
from typing import NamedTuple, Optional
```

2024-06-26 03:03 UTC, lispandfound commented on wiki/Home.md
> +[link.](https://www.pythonfordatascience.org/mixed-effects-regression-python/)](images/variable_intercept.png)
If you want the figure caption, you'll need to put it underneath the link explicitly.

2024-06-27 00:43 UTC, AndrewRidden-Harper commented on wiki/Home.md
> +[link.](https://www.pythonfordatascience.org/mixed-effects-regression-python/)](images/variable_intercept.png)
Thanks, that's good to know

2024-06-27 01:00 UTC, AndrewRidden-Harper commented on mera/mera_pymer4.py
> +class MeraResults(NamedTuple):
Thanks, that's a good suggestion

2024-06-27 02:40 UTC, lispandfound approved these changes, later dismissed

2024-06-27 04:08 UTC, sungeunbae approved these changes, later dismissed
Excellent work

2024-06-27 04:34 UTC, lispandfound requested changes

2024-06-27 04:34 UTC, lispandfound commented on requirements.txt
> +pymer4 @ https://github.com/ucgmsim/pymer4.git@get_ranef_cond_std
```suggestion
pymer4 @ git+https://github.com/ucgmsim/pymer4.git@get_ranef_cond_std
```

2024-07-02 01:14 UTC, joelridden approved these changes, later dismissed

2024-07-03 05:25 UTC, AndrewRidden-Harper commented
The requirements file now specifies our version of Pymer4 (thanks @lispandfound , I committed your code suggestion)

2024-07-03 21:45 UTC, lispandfound approved these changes

2024-07-04 01:25 UTC, joelridden approved these changes

2024-07-04 02:24 UTC, merged