Bug fix & minor improvements & remove statsmodel approach
ucgmsim/mera pull request #9
Opened 2024-07-30 02:13 UTC by claudio525

- Simplifies importing
- Adds save/load functionality for MeraResults
- Fixes minor bug
- Remove statsmodel method (not used)

2024-07-30 03:46 UTC, joelridden approved these changes, later dismissed
Just need to remove the 'statsmodels' in the requirements.txt for deptry. Rest looks good

2024-07-30 04:02 UTC, lispandfound requested changes

2024-07-30 04:02 UTC, lispandfound commented on mera/mera_pymer4.py
> +    mask: pd.DataFrame = None,
```suggestion
    mask: Optional[pd.DataFrame] = None,
```

2024-07-30 21:41 UTC, sungeunbae approved these changes

2024-07-30 22:04 UTC, joelridden approved these changes

2024-07-31 05:30 UTC, AndrewRidden-Harper approved these changes
nice updates

2024-08-01 04:53 UTC, lispandfound approved these changes

2024-08-01 19:30 UTC, merged